<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DocLoupe.Excel.Model/DocLoupe.Excel.Model.csproj" />
    <ProjectReference Include="../DocLoupe.Excel.Package/DocLoupe.Excel.Package.csproj" />
  </ItemGroup>
</Project>
